insert into producto (id, nombre, precio) values ( 1, 'Juice - Orange, Concentrate', 91);
insert into producto (id, nombre, precio) values ( 2, 'Beef - Ground, Extra Lean, Fresh', 87);
insert into producto (id, nombre, precio) values ( 3, 'Cheese - Parmesan Grated', 39);
insert into producto (id, nombre, precio) values ( 4, 'Cups 10oz Trans', 67);
insert into producto (id, nombre, precio) values ( 5, 'Wine - Beringer Founders Estate', 27);
insert into producto (id, nombre, precio) values ( 6, 'Bread - Wheat Baguette', 82);
insert into producto (id, nombre, precio) values ( 7, 'Quail - Eggs, Fresh', 3);
insert into producto (id, nombre, precio) values ( 8, 'Cheese - Mascarpone', 97);
insert into producto (id, nombre, precio) values ( 9, 'Mace', 25);
insert into producto (id, nombre, precio) values ( 10, 'Oil - Shortening - All - Purpose', 63);
insert into producto (id, nombre, precio) values ( 11, 'Marjoram - Fresh', 60);
insert into producto (id, nombre, precio) values ( 12, 'Turnip - White', 74);
insert into producto (id, nombre, precio) values ( 13, 'Pork Salted Bellies', 38);
insert into producto (id, nombre, precio) values ( 14, 'Longos - Greek Salad', 15);
insert into producto (id, nombre, precio) values ( 15, 'Amaretto', 85);
insert into producto (id, nombre, precio) values ( 16, 'Godiva White Chocolate', 97);
insert into producto (id, nombre, precio) values ( 17, 'Tomatoes - Roma', 61);
insert into producto (id, nombre, precio) values ( 18, 'Oven Mitt - 13 Inch', 1);
insert into producto (id, nombre, precio) values ( 19, 'Vermouth - White, Cinzano', 72);
insert into producto (id, nombre, precio) values ( 20, 'Club Soda - Schweppes, 355 Ml', 38);
insert into producto (id, nombre, precio) values ( 21, 'Fenngreek Seed', 1);
insert into producto (id, nombre, precio) values ( 22, 'Dill Weed - Dry', 72);
insert into producto (id, nombre, precio) values ( 23, 'Pepper - Green', 56);
insert into producto (id, nombre, precio) values ( 24, 'Bacardi Breezer - Tropical', 35);
insert into producto (id, nombre, precio) values ( 25, 'Wine - Merlot Vina Carmen', 14);
insert into producto (id, nombre, precio) values ( 26, 'Sauce - Black Current, Dry Mix', 9);
insert into producto (id, nombre, precio) values ( 27, 'Crab - Soft Shell', 17);
insert into producto (id, nombre, precio) values ( 28, 'Jameson Irish Whiskey', 19);
insert into producto (id, nombre, precio) values ( 29, 'Muffin Chocolate Individual Wrap', 77);
insert into producto (id, nombre, precio) values ( 30, 'Mussels - Frozen', 95);
